### PR TITLE
Added the test suite for python.

### PR DESCRIPTION
**Pull request by ajratnam**
### The aim of this PR?
This PR adds the test suite for python.
It also fixes a few spelling mistakes in `lcm.py` and `loop_1.c`

### How to use this testing program?
`python test.py <program.py>`

### Additional Notes
This test suite only works by checking whether the respective
`even` or `odd` exists in the next line after the input

### Valid output Example
Enter your number - `(input)`
Your number is `even`

### Invalid output Example
Enter your number - `(input)`
Please wait while I am calculating.
Your number is `even`

### CODE REVIEW

**Comment by ajratnam** [comment]
@niyoj  Finally made this test suite. Please let me know if this is ok? or any updates needed.

**Comment by ajratnam** [comment]
I did run the tests before submitting and it worked fine.

**Comment by ajratnam** [comment]
@niyoj ?

**Comment by niyoj** [comment]
Sorry was offline due to some network issues. Now I am reviewing this PR.

**Comment by ajratnam** [comment]
So what do you think?

**Comment by niyoj** [comment]
@ajratnam Sorry for the delay. I am quite unsure about adding this feature in my repo. So for now I will label your PR as `hacktoberfest-accepted` but won't merge the PR. I will be mentioning you whenever I think this will be necessary.

Thanks for contributing.

**Pull request closed without merging**
