### PR TITLE
Added LCM method in python

### PR DESCRIPTION
**Pull request by ajratnam**
### The aim of this PR?
This PR adds the LCM method to find if the number is even or odd in python.
It also fixes a few spelling mistakes in [README.md](https://github.com/niyoj/even_odd_number/blob/master/README.md).

### What is not covered in this PR?
This PR does not add the test file to check the validity of the program.

### CODE REVIEW

**Comment by ajratnam** [comment]
I have to re-think on how to make the cli script because

- I want this script to be usable by all the contributors in python.
- I don't want to limit the function name to **is_even**
- Considering other C programs, I need to think on how to make the test work without forcing the user to make a function.

**Comment by ajratnam** [comment]
I would like this PR to be a part of hacktoberfest.

**Comment by ajratnam** [comment]
Is this PR ok? or should I change anything?

**Comment by niyoj** [comment]
@ajrathum Your PR is ok and I have merged it to the main repo.

**Comment by ajratnam** [comment]
@niyoj  Glad to hear that!!, Can you add the **hacktoberfest-accepted** label?

**Pull request merged**
